services:
  - type: web
    name: elo-ranking-api
    env: node
    region: ohio
    plan: free
    buildCommand: npm install --include=dev && npm run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        value: https://elo-ranking-itmab.vercel.app
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: APP_URL
        sync: false
